"""empty message

Revision ID: 52c80b2c0391
Revises: e51c8dee9c7c
Create Date: 2018-11-03 11:36:16.740071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52c80b2c0391'
down_revision = 'e51c8dee9c7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'completed')
    # ### end Alembic commands ###
