"""empty message

Revision ID: aec5b7dc28ab
Revises: 52c80b2c0391
Create Date: 2018-11-03 12:40:35.134715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aec5b7dc28ab'
down_revision = '52c80b2c0391'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('methods', sa.Text(), nullable=True))
    op.add_column('job', sa.Column('uploaded', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'uploaded')
    op.drop_column('job', 'methods')
    # ### end Alembic commands ###
