"""empty message

Revision ID: e51c8dee9c7c
Revises: 
Create Date: 2018-11-03 11:19:13.964045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e51c8dee9c7c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('hash', sa.String(length=32), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('result_dir', sa.String(length=200), nullable=True),
    sa.Column('result_zip', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash'),
    sa.UniqueConstraint('result_dir'),
    sa.UniqueConstraint('result_zip'),
    sa.UniqueConstraint('source')
    )
    op.create_index(op.f('ix_job_name'), 'job', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_name'), table_name='job')
    op.drop_table('job')
    # ### end Alembic commands ###
