"""empty message

Revision ID: ef231d0dc8ec
Revises: 7b4295d5f6f9
Create Date: 2018-11-03 14:52:29.791046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef231d0dc8ec'
down_revision = '7b4295d5f6f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('complete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'complete')
    # ### end Alembic commands ###
